/*
 * FireCast Wildfire Monitor - Interactive Dashboard
 * 
 * This dashboard visualizes predicted fire perimeters generated by our
 * construction algorithm alongside actual CAL FIRE boundaries. Users can
 * explore fires by year, view progression through observation windows, and
 * compare predicted vs actual perimeters.
 * 
 * Features:
 * - Interactive Leaflet map displaying all fire perimeters
 * - Year filtering (2021-2025) to explore different satellite eras
 * - Fire detail panel with timeline scrubbing through observation windows
 * - Animated playback of fire progression
 * - Statistics display: area, duration, spread rates, evaluation metrics
 * - Toggle visibility of predicted and CAL FIRE perimeters
 * - Area and spread rate charts using Chart.js
 * 
 * Data Sources:
 * - fire_data.json: Metadata and metrics for all fires
 * - perimeters/{fire_id}.json: GeoJSON perimeters for each fire
 * 
 * Dependencies:
 * - Leaflet.js: Map rendering
 * - Chart.js: Statistical charts
 * 
 * Full dashboard code created with assistance from Claude (Anthropic).
 */

let fireData = [];
let selectedFire = null;
let currentWindow = 0;
let isPlaying = false;
let playTimer = null;
let map;
let overviewLayers = [];
let predLayer = null;
let actualLayer = null;
let currentPerimeters = null;
let areaChart = null;
let spreadChart = null;

document.addEventListener("DOMContentLoaded", async () => {
    initMap();
    await loadData();
    setupEvents();
});

function initMap() {
    map = L.map("map", { center: [37.2, -119.5], zoom: 6 });
    L.tileLayer(
        "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
        { maxZoom: 18 }
    ).addTo(map);
}

async function loadData() {
    const res = await fetch("dashboard_data/fire_data.json");
    if (res.ok) fireData = await res.json();
    renderOverview();
}

function renderOverview() {
    // Clear existing overview layers
    overviewLayers.forEach((l) => map.removeLayer(l));
    overviewLayers = [];
    
    if (selectedFire) return;

    const yearFilter = document.querySelector(".year-btn.active").dataset.year;

    fireData.forEach(async (fire) => {
        if (yearFilter !== "all" && fire.year.toString() !== yearFilter) return;

        try {
            const res = await fetch(`dashboard_data/perimeters/${fire.fire_id}.json`);
            if (res.ok) {
                const perimData = await res.json();
                const windowFeatures = perimData.features.filter(
                    (f) => f.properties.window_idx !== undefined
                );
                const finalWindow = windowFeatures.reduce(
                    (max, f) => f.properties.window_idx > (max?.properties?.window_idx ?? -1) ? f : max,
                    null
                );

                if (finalWindow) {
                    const layer = L.geoJSON(finalWindow, {
                        style: { color: "#f85149", weight: 2, fillColor: "#f85149", fillOpacity: 0.3 }
                    });
                    layer.on("click", () => selectFire(fire));
                    layer.addTo(map);
                    overviewLayers.push(layer);
                }
            }
        } catch (e) {}
    });
}

async function selectFire(fire) {
    selectedFire = fire;
    currentWindow = fire.windows.length - 1;

    overviewLayers.forEach((l) => map.removeLayer(l));
    overviewLayers = [];

    await loadPerimeters(fire.fire_id);

    document.getElementById("detailPanel").classList.add("open");
    document.getElementById("detailName").textContent = `${fire.name} Fire`;
    document.getElementById("badgeF125").textContent = `F1.25: ${fire.f125.toFixed(3)}`;
    document.getElementById("badgeIoU").textContent = `IoU: ${fire.iou.toFixed(3)}`;

    const slider = document.getElementById("slider");
    slider.max = fire.windows.length - 1;
    slider.value = currentWindow;

    updateStats();
    updateTimeline();
    renderCharts();
    updateMapLayers();

    // Fit map to fire bounds with padding for detail panel
    if (currentPerimeters) {
        const allCoords = [];
        currentPerimeters.features.forEach(f => {
            if (f.geometry && f.geometry.coordinates) {
                const extractCoords = (coords) => {
                    if (typeof coords[0] === 'number') {
                        allCoords.push([coords[1], coords[0]]);
                    } else {
                        coords.forEach(c => extractCoords(c));
                    }
                };
                extractCoords(f.geometry.coordinates);
            }
        });
        if (allCoords.length > 0) {
            const bounds = L.latLngBounds(allCoords);
            map.fitBounds(bounds, { paddingBottomRight: [0, 400], paddingTopLeft: [0, 20] });
        }
    } else {
        map.setView(fire.centroid, 11);
    }
}

async function loadPerimeters(fireId) {
    try {
        const res = await fetch(`dashboard_data/perimeters/${fireId}.json`);
        currentPerimeters = res.ok ? await res.json() : null;
    } catch (e) {
        currentPerimeters = null;
    }
}

function updateMapLayers() {
    if (predLayer) map.removeLayer(predLayer);
    if (actualLayer) map.removeLayer(actualLayer);
    if (!currentPerimeters || !selectedFire) return;

    const showPred = !document.getElementById("togglePred").classList.contains("off");
    const showActual = !document.getElementById("toggleActual").classList.contains("off");

    const windowFeature = currentPerimeters.features.find((f) => f.properties.window_idx === currentWindow);
    const actualFeature = currentPerimeters.features.find((f) => f.properties.type === "calfire_actual");

    if (showActual && actualFeature) {
        actualLayer = L.geoJSON(actualFeature, {
            style: { color: "#00ff99", weight: 3, fillColor: "#00ff99", fillOpacity: 0.15, dashArray: "6, 6" }
        }).addTo(map);
    }
    if (showPred && windowFeature) {
        predLayer = L.geoJSON(windowFeature, {
            style: { color: "#ff4444", weight: 3, fillColor: "#ff4444", fillOpacity: 0.35 }
        }).addTo(map);
    }
}

function updateStats() {
    if (!selectedFire) return;
    const w = selectedFire.windows[currentWindow];
    const windows = selectedFire.windows;

    document.getElementById("statPredArea").textContent = w.area_km2.toFixed(1);
    document.getElementById("statActualArea").textContent = selectedFire.actual_area_km2.toFixed(1);
    document.getElementById("statF125").textContent = selectedFire.f125.toFixed(3);
    document.getElementById("statIoU").textContent = selectedFire.iou.toFixed(3);
    document.getElementById("statDet").textContent = w.cumulative_points.toLocaleString();

    const acres = w.area_km2 * 247.105;
    document.getElementById("statAcres").textContent = acres.toLocaleString(undefined, { maximumFractionDigits: 0 });

    if (windows.length >= 2 && windows[0].timestamp && windows[windows.length - 1].timestamp) {
        const start = new Date(windows[0].timestamp);
        const end = new Date(windows[windows.length - 1].timestamp);
        const days = (end - start) / (1000 * 60 * 60 * 24);
        document.getElementById("statDuration").textContent = days.toFixed(1);
    } else {
        document.getElementById("statDuration").textContent = "--";
    }

    const spreadRates = [];
    for (let i = 1; i < windows.length; i++) {
        const areaDiffAcres = (windows[i].area_km2 - windows[i - 1].area_km2) * 247.105;
        const hoursDiff = (new Date(windows[i].timestamp) - new Date(windows[i - 1].timestamp)) / (1000 * 60 * 60);
        if (hoursDiff > 0 && areaDiffAcres > 0) spreadRates.push(areaDiffAcres / hoursDiff);
    }

    if (spreadRates.length > 0) {
        document.getElementById("statPeakSpread").textContent = Math.max(...spreadRates).toFixed(0);
        document.getElementById("statAvgSpread").textContent = (spreadRates.reduce((a, b) => a + b, 0) / spreadRates.length).toFixed(0);
    } else {
        document.getElementById("statPeakSpread").textContent = "--";
        document.getElementById("statAvgSpread").textContent = "--";
    }
}

function updateTimeline() {
    if (!selectedFire) return;
    const w = selectedFire.windows[currentWindow];

    document.getElementById("windowNum").textContent = `Window ${currentWindow + 1}/${selectedFire.windows.length}`;

    if (w.timestamp) {
        const d = new Date(w.timestamp);
        document.getElementById("timelineDate").textContent = d.toLocaleDateString("en-US", {
            month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit"
        });
    }
}

function renderCharts() {
    if (!selectedFire) return;

    const windows = selectedFire.windows;
    const labels = windows.map((_, i) => `W${i + 1}`);
    const areas = windows.map((w) => w.area_km2);

    const spreadRates = [0];
    for (let i = 1; i < windows.length; i++) {
        const areaDiffAcres = (windows[i].area_km2 - windows[i - 1].area_km2) * 247.105;
        const hoursDiff = (new Date(windows[i].timestamp) - new Date(windows[i - 1].timestamp)) / (1000 * 60 * 60);
        spreadRates.push(hoursDiff > 0 ? Math.max(0, areaDiffAcres / hoursDiff) : 0);
    }

    if (areaChart) areaChart.destroy();
    areaChart = new Chart(document.getElementById("areaChart"), {
        type: "bar",
        data: { labels, datasets: [{ data: areas, backgroundColor: "rgba(255,68,68,0.7)", borderRadius: 2 }] },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false } },
            scales: {
                x: { grid: { display: false }, ticks: { color: "#484f58", font: { size: 8 } } },
                y: { grid: { color: "rgba(255,255,255,0.05)" }, ticks: { color: "#484f58", font: { size: 9 } } }
            }
        }
    });

    if (spreadChart) spreadChart.destroy();
    spreadChart = new Chart(document.getElementById("spreadChart"), {
        type: "bar",
        data: { labels, datasets: [{ data: spreadRates, backgroundColor: "rgba(255,170,0,0.7)", borderRadius: 2 }] },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false } },
            scales: {
                x: { grid: { display: false }, ticks: { color: "#484f58", font: { size: 8 } } },
                y: { grid: { color: "rgba(255,255,255,0.05)" }, ticks: { color: "#484f58", font: { size: 9 } } }
            }
        }
    });
}

function togglePlay() {
    const btn = document.getElementById("playBtn");

    if (isPlaying) {
        clearInterval(playTimer);
        isPlaying = false;
        btn.textContent = "Play";
    } else {
        if (!selectedFire) return;
        isPlaying = true;
        btn.textContent = "Pause";
        currentWindow = 0;
        document.getElementById("slider").value = 0;
        updateStats();
        updateTimeline();
        updateMapLayers();

        playTimer = setInterval(() => {
            currentWindow++;
            if (currentWindow >= selectedFire.windows.length) {
                togglePlay();
                currentWindow = selectedFire.windows.length - 1;
                document.getElementById("slider").value = currentWindow;
                return;
            }
            document.getElementById("slider").value = currentWindow;
            updateStats();
            updateTimeline();
            updateMapLayers();
        }, 800);
    }
}

function setupEvents() {
    document.querySelectorAll(".year-btn").forEach((btn) => {
        btn.addEventListener("click", () => {
            document.querySelectorAll(".year-btn").forEach((b) => b.classList.remove("active"));
            btn.classList.add("active");
            renderOverview();
        });
    });

    document.getElementById("slider").addEventListener("input", (e) => {
        currentWindow = parseInt(e.target.value);
        updateStats();
        updateTimeline();
        updateMapLayers();
    });

    document.getElementById("playBtn").addEventListener("click", togglePlay);

    document.getElementById("closeBtn").addEventListener("click", () => {
        document.getElementById("detailPanel").classList.remove("open");
        if (predLayer) map.removeLayer(predLayer);
        if (actualLayer) map.removeLayer(actualLayer);
        selectedFire = null;
        currentPerimeters = null;
        map.setView([37.2, -119.5], 6);
        renderOverview();
    });

    document.getElementById("togglePred").addEventListener("click", function () {
        this.classList.toggle("off");
        updateMapLayers();
    });

    document.getElementById("toggleActual").addEventListener("click", function () {
        this.classList.toggle("off");
        updateMapLayers();
    });

    const resizeHandle = document.getElementById("resizeHandle");
    const detailPanel = document.getElementById("detailPanel");
    let isResizing = false;

    resizeHandle.addEventListener("mousedown", (e) => { isResizing = true; e.preventDefault(); });
    document.addEventListener("mousemove", (e) => {
        if (!isResizing) return;
        const newHeight = Math.min(Math.max(window.innerHeight - e.clientY, 200), window.innerHeight * 0.7);
        detailPanel.style.height = newHeight + "px";
    });
    document.addEventListener("mouseup", () => { isResizing = false; });
}
